project:
  type: book
  output-dir: docs
  resources:
    - atlas.json
    - images/cran-package-ggplot2-clean.png
    - images/cran-checks-usethis-clean.png

bibliography: book.bib

book:
  title: "Paquetes de R"
  reader-mode: true
  site-url: https://davidrsch.github.io/rpkgs-es/
  
  page-footer: 
    left: |
      Paquetes de R fue escrito por Hadley Wickham y Jenny Bryan
    right: |
      Este libro fue creado usando <a href="https://quarto.org/">Quarto</a>.
  cover-image: images/cover-2e-small.png
  favicon: logo.png
  
  author:
    - name: HADLEY WICKHAM
    - name: "&"
    - name: JENNY BRYAN
  description: |
    Aprenda a crear un paquete, la unidad fundamental de contenido compartible, reutilizable,
    y c贸digo R reproducible.
  search: true
  sidebar: 
    pinned: true
    tools: 
      - icon: github
        menu: 
          - text: Original
            url: https://github.com/hadley/r-pkgs/
          - text: Traducci贸n
            url: https://github.com/davidrsch/rpkgs-es
  page-navigation: true
  
  chapters:
  - index.qmd
  - preface.qmd
  - introduction.qmd
  
  - part: Empezando
    chapters: 
    - whole-game.qmd
    - setup.qmd
    - structure.qmd
    - workflow101.qmd
    - package-within.qmd
  
  - part: Componentes de un paquete
    chapters:
    - code.qmd
    - data.qmd
    - misc.qmd
  
  - part: Metadatos del paquete
    chapters:
    - description.qmd
    - dependencies-mindset-background.qmd
    - dependencies-in-practice.qmd
    - license.qmd
  
  - part: Probar
    chapters:
    - testing-basics.qmd
    - testing-design.qmd
    - testing-advanced.qmd
    
  - part: Documentaci贸n
    chapters:
    - man.qmd
    - vignettes.qmd
    - other-markdown.qmd
    - website.qmd
  
  - part: Mantenimiento y distribuci贸n
    chapters:
    - software-development-practices.qmd
    - lifecycle.qmd
    - release.qmd    

  - references.qmd
  
  appendices:
    - R-CMD-check.qmd

lang: es

format:
  html:
    theme: [cosmo, custom.scss]
    code-link: true
    author-meta: "Hadley Wickham y Jenny Bryan"
    include-in-header: "plausible.html"
    include-after-body: [ddrsch_script.html]
  asciidoc: default
  
editor: visual
